# Loading the needed libraries.

It's is indeed useful skill to organize your notebooks folowwing some structue, so futher when you will operate with a bunch of code lines you will have lower probability to mess it up

In [1]:
import pandas as pd
import numpy as np

# Numpy

NumPy is the fundamental package for scientific computing with Python. 
It contains various features including these important ones:
- A powerful N-dimensional array object
- Sophisticated (broadcasting) functions
- Tools for integrating C/C++ and Fortran code
- Useful linear algebra, Fourier transform, and random number capabilities

NumPy’s main object is the homogeneous multidimensional array.

    It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
    In NumPy dimensions are called axes. 
    The number of axes is rank.
    NumPy’s array class is called ndarray. It is also known by the alias array.

As you will practice with Numpy library, you will not need to use any additional files to extract data. For now, just use random numbers as initial data

#### Task #1. Create the numpy array, as shown below. 

In [78]:
# Your code goes here, don't run the cell with answer.
#1___

#a = np.array(range(14))
#a
#2___

#print("array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])")

#3___

#a = list(range(14))
#print("array(", a, ")")

#4___

a = np.arange(14)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [8]:
#Ouptup - Don't run this cell!

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

#### Task #2 Create a 3×3 numpy array of all False’s

In [11]:
# Your code goes here, don't run the cell with answer below.
#1___

a = np.full((3, 3), False)
a

#2___

#print("array([[False, False, False],\n       [False, False, False],\n       [False, False, False]])")

#3___
#a = np.zeros((3, 3), dtype=bool)
#a


array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [10]:
#Ouptup - Don't run this cell!

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

#### Task #3 Show only numbers those satisfy given conditions:
    - Are even
    - Are odd
    - Can be divided by 5
 Use an array you have created for task #1

In [124]:
# Your code goes here, don't run the cell with answer below.
#1___

#a = np.array(range(0, 14, 2))
#print("Evens", a)
#a = np.array(range(1, 14, 2))
#print("Odds ", a)
#a = np.array(range(0, 11, 5))
#print("Goods", a)

#2___

#a = str([x for x in range(0, 14, 2)]).replace(",", "")
#print("Evens", a)
#a = str([x for x in range(1, 14, 2)]).replace(",", "")
#print("Odds ", a)
#a = str([x for x in range(0, 14, 5)]).replace(",", "")
#print("Goods", a)

#3___
#print("Evens [0 2 4 6 8 10 12]\nOdds  [1 3 5 7 9 11 13]\nGoods [0 5 10]")

#4___

#a = np.array(range(14))
#id = (a % 2 == 0)
#print("Evens", a[id])
#id = (a % 2 != 0)
#print("Odd  ", a[id])
#id = (a % 5 == 0)
#print("Goods", a[id])

#5___
a = np.arange(0, 14, 2)
print("Evens", a)
a = np.arange(1, 14, 2)
print("Odds ", a)
a = np.arange(0, 11, 5)
print("Goods", a)


Evens [ 0  2  4  6  8 10 12]
Odds  [ 1  3  5  7  9 11 13]
Goods [ 0  5 10]


In [28]:
#Ouptup - Don't run this cell!

Evens [ 0  2  4  6  8 10 12]
Odds  [ 1  3  5  7  9 11 13]
Goods [ 0  5 10]


#### Task #4. Create a 5×5 numpy array of random real numbers

In [52]:
# Your code goes here, don't run the cell with answer below. Note that you can obtain different numbers
#1___

#np.random.rand(5,5)

#2___

a = []
for i in range(5):
    for i in range(5):
        a.append(np.random.normal())
np.array(a)


array([-0.91359085, -2.32190828,  0.0031509 , -0.57335799, -2.12479151,
       -2.15439005,  1.69559739,  0.04569032,  0.02417637,  0.13183985,
        2.40748637,  1.76467771,  0.19999292, -0.66677873, -0.17287936,
       -1.2290543 ,  0.50013669,  2.0121277 , -0.93224244, -1.46980088,
       -1.07333051, -1.05757865,  0.45712905,  0.67707345,  1.27400899])

In [45]:
#Ouptup - Don't run this cell!

array([[ 0.63283481, -0.04419987,  1.61845131,  1.27253246, -0.07385166],
       [-0.28427694,  0.48554145, -1.36759869,  0.06758673, -1.09818961],
       [ 0.6130752 ,  0.55675975, -0.31003258,  0.91985871,  1.76519441],
       [ 0.69524943,  0.22457112,  0.77304183,  1.02987713, -0.03404809],
       [-1.42999758, -0.19161166,  1.16199858,  0.03341245, -1.45857607]])

#### Task #5. Create a numpy array of 9 random numbers between 900 and 1001.

In [70]:
# Your code goes here, don't run the cell with answer below. Note that you can obtain different numbers
#1___

#np.random.randint(low=900, high=1001, size=9)

#2___

from random import randint
a = []
for x in range(10):
    a.append(randint(900, 1002))
np.array(a)

#3
#str("array([" + str(randint(900, 1002)) + ", " + str(randint(900, 1002)) + ", " + str(randint(900, 1002))+ ", " +str(randint(900, 1002))+ ", " +str(randint(900, 1002))+ ", " +str(randint(900, 1002))+ ", " +str(randint(900, 1002))+ ", " +str(randint(900, 1002))+", " + str(randint(900, 1002)) + "])")


array([932, 917, 905, 994, 912, 940, 943, 967, 940, 976])

In [49]:
#Ouptup - Don't run this cell!

array([974, 923, 922, 920, 902, 935, 911, 967, 981])

#### Task #6. Create a numpy array 25 integer numbers. Then transform it into 5×5 array

In [47]:
# Your code goes here, don't run the cell with answer below. 
#1__

# another ways of creating numpy array were showen in ex. 1, 3, so i won't do it again!

a = np.arange(25)
a.reshape(5,5)

#2__

#a = np.empty((5,5))
#x = 0
#for i in range(5):
 #   for j in range(5):
  #      a[i, j] = int(x)
   #     x+=1
#a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
#Ouptup - Don't run this cell!

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### Task #7. Create two numpy arrays A and B (or use whatever letter taht makes you happy) as shown below, and then get the required output

In [151]:
# Your code goes here, don't run the cell with answer below. 
#1___
# another ways of creating numpy array were showen in ex. 1, 3, so i won't do it again!
a = np.arange(9)
b = np.arange(1, 18, 2)
# 1st output
(a, b)


# 2nd output
#с =np.concatenate((a, b),)
#с

# 3d output
#с.reshape(2,9)

#2___

#print("(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),\narray([ 1,  3,  5,  7,  9, 11, 13, 15, 17]))")


(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 1,  3,  5,  7,  9, 11, 13, 15, 17]))

In [62]:
#Ouptup - Don't run this cell!

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 1,  3,  5,  7,  9, 11, 13, 15, 17]))

In [65]:
#Ouptup - Don't run this cell!

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  1,  3,  5,  7,  9, 11, 13, 15,
       17])

In [64]:
#Ouptup - Don't run this cell!

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17]])

#### Task #8 Create a numpy array as shown on output

In [159]:
# Your code goes here, don't run the cell with answer below. 
#1___

#np.zeros((15,15))

#2___
np.full((15, 15), 0, dtype=float)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [30]:
#Ouptup - Don't run this cell!

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

#### Task #9 Use the array A from Task #7 and get desired output

In [169]:
# Your code goes here, don't run the cell with answer below.

#1___
a = np.arange(9)
print(a)

(a[-1], a[0], a[4]/1)

[0 1 2 3 4 5 6 7 8]


(8, 0, 4.0)

In [75]:
#Ouptup - Don't run this cell!

[0 1 2 3 4 5 6 7 8]


(8, 0, 4.0)

#### Task #10 Use the arrays A and B from Task #7 and find common numbers

In [20]:
# Your code goes here, don't run the cell with answer below.

#1___

#a = np.arange(9)
#b = np.arange(1, 18, 2)
#np.intersect1d(a,b)

#2___

a = np.arange(9)
b = np.arange(1, 18, 2)
np.array(list(set(list(a)).intersection(list(b))))

array([1, 3, 5, 7])

In [1]:
#Ouptup - Don't run this cell!

array([1, 3, 5, 7])


#### Task #11 Create a copy of array B, and change the value of its' 5-th element

In [29]:
# Your code goes here, don't run the cell with answer below.

#!!!Mistake in output array in the task!!! 10 -> 9

#1___
b = np.arange(1, 18, 2)
a = np.copy(b)
a[4] = 12
b, a

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17]),
 array([ 1,  3,  5,  7, 12, 11, 13, 15, 17]))

In [86]:
#Ouptup - Don't run this cell!

(array([ 1,  3,  5,  7, 10, 11, 13, 15, 17]),
 array([ 1,  3,  5,  7, 12, 11, 13, 15, 17]))

#### Task #12 Assign -1 to last 5 elements of the array B

In [37]:
# Your code goes here, don't run the cell with answer below.
#1___

#b = np.arange(1, 18, 2)
#b [4:10] = -1
#print(b)

#2___

b = np.arange(1, 18, 2)
for i in range(4, 9):
    b[i] = -1
print(b)

[ 1  3  5  7 -1 -1 -1 -1 -1]


In [95]:
# Don't run this cell!

[ 1  3  5  7 -1 -1 -1 -1 -1]


#### Task #13 Create 3×3 array and reverse it columns

In [60]:
# Your code goes here, don't run the cell with answer below.

#1___
#a = np.arange(9)
#a = a.reshape(3,3)
#print(a[::1, ::-1])

#2___
a = np.arange(9)
a = a.reshape(3,3)
print(np.fliplr(a))

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [104]:
#Ouptup - Don't run this cell!

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[2 1 0]
 [5 4 3]
 [8 7 6]]


#### Task #14 Create a random array of flowting point numbers and get desired output

In [125]:
# Your code goes here, don't run the cell with answer below.

#1st output

#np.random.uniform(low=1e-04, high=10e-10, size=(3, 3))

#2nd output

0.001 *np.random.random_sample((3,3))+0.0001

array([[0.0010145 , 0.00072365, 0.00018189],
       [0.00037747, 0.00018684, 0.00094319],
       [0.00026112, 0.00082339, 0.00065647]])

In [108]:
# Don't run this cell!

array([[5.43404942e-04, 2.78369385e-04, 4.24517591e-04],
       [8.44776132e-04, 4.71885619e-06, 1.21569121e-04],
       [6.70749085e-04, 8.25852755e-04, 1.36706590e-04]])

In [112]:
#Ouptup - Don't run this cell!

array([[0.000543405, 0.000278369, 0.000424518],
       [0.000844776, 0.000004719, 0.000121569],
       [0.000670749, 0.000825853, 0.000136707]])

#### Task #15 Create an array X filled by zeros , then replace random number of elements with Nans

In [288]:
# Your code goes here, don't run the cell with answer below.
from random import randint

a = np.zeros((10, 10))
#1st output
#a

a = a.flatten()
for i in range(randint(10, 50)):
    a[i] = "nan"
#2nd output

a = np.random.permutation(a)
a = a.reshape(10,10)
a

array([[ 0., nan, nan, nan,  0.,  0.,  0.,  0.,  0.,  0.],
       [nan,  0., nan, nan,  0.,  0.,  0., nan,  0.,  0.],
       [ 0., nan,  0.,  0.,  0.,  0., nan,  0.,  0.,  0.],
       [nan,  0.,  0.,  0.,  0.,  0., nan, nan,  0.,  0.],
       [ 0., nan,  0.,  0.,  0., nan,  0., nan,  0.,  0.],
       [nan,  0., nan,  0.,  0.,  0.,  0.,  0.,  0., nan],
       [nan, nan,  0., nan,  0., nan,  0., nan,  0., nan],
       [nan, nan,  0.,  0., nan,  0.,  0.,  0.,  0., nan],
       [ 0.,  0.,  0.,  0., nan, nan, nan, nan, nan, nan],
       [nan,  0.,  0., nan,  0.,  0.,  0., nan, nan,  0.]])

In [120]:
#Ouptup - Don't run this cell!

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [122]:
#Ouptup - Don't run this cell!

array([[ 0., nan,  0., nan,  0., nan, nan,  0.,  0.,  0.],
       [ 0.,  0.,  0., nan, nan,  0.,  0.,  0.,  0.,  0.],
       [nan,  0.,  0., nan, nan, nan,  0., nan,  0., nan],
       [nan,  0.,  0., nan,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., nan,  0., nan,  0.,  0.,  0.,  0.,  0.,  0.],
       [nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., nan,  0., nan,  0.,  0.,  0.,  0.,  0.],
       [ 0., nan,  0., nan,  0.,  0.,  0.,  0.,  0.,  0.],
       [nan, nan,  0., nan, nan,  0.,  0.,  0.,  0., nan],
       [ 0., nan, nan,  0.,  0.,  0.,  0.,  0., nan,  0.]])

#### Task #15.2 Calculate numbers of Nans' in X array

In [268]:
# Your code goes here, don't run the cell with answer below.
from random import randint

a = np.zeros((10, 10))

a = a.flatten()
for i in range(randint(10, 50)):
    a[i] = "nan"
    
a = np.random.permutation(a)
a = a.reshape(10,10)
print("Amount of missing values:", i)

Amount of missing values: 48


In [130]:
#Ouptup - Don't run this cell!

Amount of missing values: 29


#### Task #15.3 Print positions of Nan's for column 4

In [463]:
# Your code goes here, don't run the cell with answer below.
from random import randint

a = np.zeros((10, 10))

a = a.flatten()
for i in range(randint(10, 50)):
    a[i] = "nan"

a = np.random.permutation(a)
a = a.reshape(10,10)

aa = []
col4 = a[:, 4]
col4 = list(col4)

for i in range(10):
    col4[i]= str(col4[i])
print(col4)

for i in range(10):
    if 'nan' in col4[i]:
        aa.append(i+1)
np.array(aa)

['0.0', '0.0', '0.0', '0.0', 'nan', '0.0', 'nan', 'nan', 'nan', '0.0']


array([5, 7, 8, 9])

In [140]:
#Ouptup - Don't run this cell!

(array([1, 2, 6, 8], dtype=int64),)

### Congratulations, you have completed practice with Numpy. However, its never too much to practice. 

#### Now, it's time to start Pandas practice

In [1]:
import numpy as np
import pandas as pd


In [5]:
article_read = pd.read_csv('pandas_tutorial_read.csv', delimiter=';', names = ['my_datetime', 'event', 'country', 'user_id', 'source', 'topic'])

article_read

my_datetime event    country     user_id   source          topic
0     2018-01-01 00:01:01  read  country_7  2458151261      SEO  North America
1     2018-01-01 00:03:20  read  country_7  2458151262      SEO  South America
2     2018-01-01 00:04:01  read  country_7  2458151263  AdWords         Africa
3     2018-01-01 00:04:02  read  country_7  2458151264  AdWords         Europe
4     2018-01-01 00:05:03  read  country_8  2458151265   Reddit  North America
5     2018-01-01 00:05:42  read  country_6  2458151266   Reddit  North America
6     2018-01-01 00:06:06  read  country_2  2458151267   Reddit         Europe
7     2018-01-01 00:06:15  read  country_6  2458151268  AdWords         Europe
8     2018-01-01 00:07:21  read  country_7  2458151269  AdWords  North America
9     2018-01-01 00:07:29  read  country_5  2458151270   Reddit  North America
10    2018-01-01 00:07:57  read  country_5  2458151271  AdWords           Asia
11    2018-01-01 00:08:57  read  country_7  2458151272      SEO      Australia
12    2018-01-01 00:09:11  read  country_5  2458151273   Reddit           Asia
13    2018-01-01 00:09:29  read  country_2  2458151274   Reddit         Europe
14    2018-01-01 00:11:06  read  country_7  2458151275   Reddit         Africa
15    2018-01-01 00:11:22  read  country_7  2458151276      SEO  North America
16    2018-01-01 00:13:05  read  country_8  2458151277      SEO  North America
17    2018-01-01 00:13:06  read  country_2  2458151278   Reddit           Asia
18    2018-01-01 00:13:39  read  country_4  2458151279      SEO  North America
19    2018-01-01 00:14:53  read  country_2  2458151280   Reddit           Asia
20    2018-01-01 00:15:44  read  country_2  2458151281   Reddit           Asia
21    2018-01-01 00:15:50  read  country_7  2458151282   Reddit         Africa
22    2018-01-01 00:17:15  read  country_2  2458151283  AdWords         Europe
23    2018-01-01 00:17:31  read  country_2  2458151284   Reddit           Asia
24    2018-01-01 00:17:58  read  country_7  2458151285   Reddit         Africa
25    2018-01-01 00:18:55  read  country_2  2458151286  AdWords  North America
26    2018-01-01 00:20:18  read  country_5  2458151287      SEO  North America
27    2018-01-01 00:20:44  read  country_2  2458151288      SEO  North America
28    2018-01-01 00:23:16  read  country_2  2458151289   Reddit           Asia
29    2018-01-01 00:23:51  read  country_7  2458151290   Reddit           Asia
...                   ...   ...        ...         ...      ...            ...
1765  2018-01-01 23:41:11  read  country_2  2458153026   Reddit         Africa
1766  2018-01-01 23:41:51  read  country_5  2458153027  AdWords           Asia
1767  2018-01-01 23:43:54  read  country_5  2458153028  AdWords         Europe
1768  2018-01-01 23:44:52  read  country_8  2458153029   Reddit  South America
1769  2018-01-01 23:45:09  read  country_5  2458153030  AdWords      Australia
1770  2018-01-01 23:45:12  read  country_6  2458153031   Reddit           Asia
1771  2018-01-01 23:45:56  read  country_5  2458153032  AdWords         Africa
1772  2018-01-01 23:45:58  read  country_7  2458153033      SEO  South America
1773  2018-01-01 23:46:13  read  country_8  2458153034   Reddit           Asia
1774  2018-01-01 23:46:22  read  country_2  2458153035  AdWords           Asia
1775  2018-01-01 23:47:19  read  country_2  2458153036  AdWords           Asia
1776  2018-01-01 23:49:04  read  country_6  2458153037   Reddit           Asia
1777  2018-01-01 23:49:52  read  country_5  2458153038      SEO  North America
1778  2018-01-01 23:51:17  read  country_2  2458153039   Reddit           Asia
1779  2018-01-01 23:51:25  read  country_4  2458153040      SEO  South America
1780  2018-01-01 23:51:46  read  country_8  2458153041  AdWords         Africa
1781  2018-01-01 23:51:52  read  country_2  2458153042   Reddit           Asia
1782  2018-01-01 23:53:03  read  country_2  2458153043  AdWords           Asia
1783  2018-01-01 23:53:33  read  country_3  2458153044   Reddit 

In [6]:
article_read[['user_id','topic', 'country']][article_read.country == 'country_2'].head()

user_id   topic    country
6   2458151267  Europe  country_2
13  2458151274  Europe  country_2
17  2458151278    Asia  country_2
19  2458151280    Asia  country_2
20  2458151281    Asia  country_2